[package]
name = "proxmox-tfa"
version = "2.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "tfa implementation for totp and u2f"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base32 = "0.4"
base64.workspace = true
hex.workspace = true
openssl.workspace = true
percent-encoding.workspace = true
serde.workspace = true
serde_plain = "1.0"
serde_json = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
url.workspace = true

proxmox-schema = { version = "1", path = "../proxmox-schema", features = [ "api-macro" ], optional = true }
proxmox-time = { version = "1", path = "../proxmox-time", optional = true }
proxmox-uuid = { version = "1", path = "../proxmox-uuid", optional = true }
webauthn-rs = { version = "0.3", optional = true }

[features]
default = []
u2f = [ "dep:libc", "dep:serde_json", "serde/derive" ]
api = [ "u2f", "dep:webauthn-rs", "dep:proxmox-uuid", "dep:proxmox-time" ]
api-types = [ "dep:proxmox-schema" ]
