[package]
name = "proxmox-tfa"
version = "2.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
description = "tfa implementation for totp and u2f"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
base32 = "0.4"
base64 = "0.13"
hex = "0.4"
openssl = "0.10"
percent-encoding = "2.1"
serde = "1.0"
serde_plain = "1.0"
serde_json = { version = "1.0", optional = true }
libc = { version = "0.2", optional = true }
url = "2.2"

proxmox-schema = { version = "1", path = "../proxmox-schema", features = [ "api-macro" ], optional = true }
proxmox-time = { version = "1", path = "../proxmox-time", optional = true }
proxmox-uuid = { version = "1", path = "../proxmox-uuid", optional = true }
webauthn-rs = { version = "0.3", optional = true }

[features]
default = []
u2f = [ "dep:libc", "dep:serde_json", "serde/derive" ]
api = [ "u2f", "dep:webauthn-rs", "dep:proxmox-uuid", "dep:proxmox-time" ]
api-types = [ "dep:proxmox-schema" ]
