[workspace]
members = [
    "proxmox",
    "proxmox-api-macro",
    "proxmox-borrow",
    "proxmox-http",
    "proxmox-sortable-macro",
    "proxmox-tfa",
    "proxmox-uuid",
]
exclude = [
    "build",
]
