[workspace]
members = [
    "proxmox-api-macro",
    "proxmox-async",
    "proxmox-borrow",
    "proxmox-compression",
    "proxmox-http",
    "proxmox-io",
    "proxmox-lang",
    "proxmox-metrics",
    "proxmox-rest-server",
    "proxmox-router",
    "proxmox-schema",
    "proxmox-serde",
    "proxmox-shared-memory",
    "proxmox-section-config",
    "proxmox-sortable-macro",
    "proxmox-subscription",
    "proxmox-sys",
    "proxmox-tfa",
    "proxmox-time",
    "proxmox-uuid",
]
exclude = [
    "build",
]
[workspace.package]
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox.git"
exclude = [ "debian" ]
