[workspace]
members = [
    "proxmox",
    "proxmox-api-macro",
    "proxmox-borrow",
    "proxmox-http",
    "proxmox-io",
    "proxmox-lang",
    "proxmox-router",
    "proxmox-schema",
    "proxmox-sortable-macro",
    "proxmox-tfa",
    "proxmox-time",
    "proxmox-uuid",
]
exclude = [
    "build",
]
