[package]
name = "proxmox-acme-rs"
version = "0.1.2"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "ACME client library"
exclude = [
    "build",
    "debian",
]

[dependencies]
base64 = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = "0.10.29"

curl = { version = "0.4.33", optional = true }

[features]
default = []
client = ["curl"]

[dev-dependencies]
anyhow = "1.0"
