[workspace]
members = [
    "proxmox-api-macro",
    "proxmox-async",
    "proxmox-borrow",
    "proxmox-compression",
    "proxmox-http",
    "proxmox-io",
    "proxmox-lang",
    "proxmox-metrics",
    "proxmox-rest-server",
    "proxmox-router",
    "proxmox-schema",
    "proxmox-serde",
    "proxmox-shared-memory",
    "proxmox-section-config",
    "proxmox-sortable-macro",
    "proxmox-subscription",
    "proxmox-sys",
    "proxmox-tfa",
    "proxmox-time",
    "proxmox-uuid",
]
exclude = [
    "build",
]
[workspace.package]
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
repository = "https://git.proxmox.com/?p=proxmox.git"
exclude = [ "debian" ]

[workspace.dependencies]
# any features enabled here are enabled on all members using 'workspace = true'!

# external dependencies
anyhow = "1.0"
base64 = "0.13"
endian_trait = "0.6"
futures = "0.3"
hex = "0.4"
http = "0.2"
hyper = "0.14.5"
lazy_static = "1.4"
libc = "0.2.107"
log = "0.4.17"
nix = "0.24.1"
openssl = "0.10"
percent-encoding = "2.1"
proc-macro2 = "1.0"
quote = "1.0"
serde = "1.0"
serde_json = "1.0"
syn = { version = "1.0", features = [ "full", "visit-mut" ] }
tokio = "1.6"
tokio-openssl = "0.6.1"
url = "2.2"
zstd = { version = "0.6", features = [ "bindgen" ] }

# workspace dependencies
proxmox-api-macro = { version = "1.0.3", path = "proxmox-api-macro" }
proxmox-async = { version = "0.4.1", path = "proxmox-async" }
proxmox-compression = { version = "0.1.1", path = "proxmox-compression" }
proxmox-http = { version = "0.7", path = "proxmox-http" }
proxmox-io = { version = "1.0.0", path = "proxmox-io" }
proxmox-lang = { version = "1.1", path = "proxmox-lang" }
proxmox-router = { version = "1.3.0", path = "proxmox-router" }
proxmox-schema = { version = "1.3.3", path = "proxmox-schema" }
proxmox-serde = { version = "0.1.1", path = "proxmox-serde", features = [ "serde_json" ] }
proxmox-sortable-macro = { version = "0.1.2", path = "proxmox-sortable-macro" }
proxmox-sys = { version = "0.4", path = "proxmox-sys" }
proxmox-time = { version = "1.1", path = "proxmox-time" }
proxmox-uuid = { version = "1", path = "proxmox-uuid" }
