[package]
name = "proxmox-apt"
version = "0.8.0"
authors = [
    "Fabian Ebner <f.ebner@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2018"
license = "AGPL-3"
description = "Proxmox library for APT"
homepage = "https://www.proxmox.com"

exclude = [ "debian" ]

[lib]
name = "proxmox_apt"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
hex = "0.4.3"
once_cell = "1.3.1"
openssl = "0.10"
serde = { version = "1.0", features = ["derive"] }

proxmox-schema = { version = "1", features = [ "api-macro" ] }
