[workspace]
members = [
    "proxmox-api-macro",
    "proxmox-async",
    "proxmox-borrow",
    "proxmox-compression",
    "proxmox-http",
    "proxmox-io",
    "proxmox-lang",
    "proxmox-metrics",
    "proxmox-router",
    "proxmox-schema",
    "proxmox-serde",
    "proxmox-shared-memory",
    "proxmox-section-config",
    "proxmox-sortable-macro",
    "proxmox-subscription",
    "proxmox-sys",
    "proxmox-tfa",
    "proxmox-time",
    "proxmox-uuid",
]
exclude = [
    "build",
]
