[package]
name = "proxmox-openid"
version = "0.5.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
exclude = [
    "build",
    "debian",
]

[lib]
name = "proxmox_openid"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.1"
http = "0.2"
curl = { version = "0.4.33" }
proxmox = { version = "0.11.5",  default-features = false }
nix = "0.19.1"
openidconnect = { version = "2.0", default-features = false, features = ["curl"] }
