[package]
name = "proxmox"
edition = "2018"
version = "0.15.1"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
license = "AGPL-3"
description = "Generic Proxmox library"

exclude = [ "debian" ]

[dependencies]
# General dependencies
anyhow = "1.0"
lazy_static = "1.4"
libc = "0.2"
nix = "0.19.1"
unicode-width ="0.1.8"

# tools module:
base64 = "0.12"
endian_trait = { version = "0.6", features = ["arrays"] }
regex = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = [], optional = true }

# Macro crates:
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true, version = "0.1.1" }

proxmox-io = { path = "../proxmox-io", version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", version = "1.0.0" }
proxmox-schema = { path = "../proxmox-schema", version = "1.0.0" }
proxmox-time = { path = "../proxmox-time", version = "1.0.0" }

[dev-dependencies]
tokio = "1.0"

[features]
default = []
sortable-macro = ["proxmox-sortable-macro"]
