[package]
name = "proxmox"
edition = "2018"
version = "0.1.0"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
proxmox-api = { path = "../proxmox-api" }
proxmox-api-macro = { path = "../proxmox-api-macro" }
proxmox-sys = { path = "../proxmox-sys" }
proxmox-tools = { path = "../proxmox-tools" }

[features]
default = []
valgrind = ["proxmox-tools/valgrind"]
