[package]
name = "proxmox"
edition = "2018"
version = "0.1.1-dev.1"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
proxmox-api = { path = "../proxmox-api", default-features = false }
proxmox-api-macro = { path = "../proxmox-api-macro", optional = true }
proxmox-sys = { path = "../proxmox-sys" }
proxmox-tools = { path = "../proxmox-tools" }
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true }

[features]
api-macro = ["proxmox-api-macro"]
cli = ["proxmox-api/cli"]
default = [ "router", "cli" ]
router = ["proxmox-api/router"]
sortable-macro = ["proxmox-sortable-macro"]
valgrind = ["proxmox-tools/valgrind"]
