[package]
name = "proxmox"
edition = "2018"
version = "0.13.5"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
license = "AGPL-3"
description = "Proxmox library"

exclude = [ "debian" ]

[dependencies]
# General dependencies
anyhow = "1.0"
lazy_static = "1.4"
libc = "0.2"
nix = "0.19.1"
unicode-width ="0.1.8"

# tools module:
base64 = "0.12"
endian_trait = { version = "0.6", features = ["arrays"] }
regex = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
#valgrind_request = { git = "https://github.com/edef1c/libvalgrind_request", version = "1.1.0", optional = true }
# libc, nix, lazy_static

# sys module:
# libc, nix, lazy_static

# api module:
bytes = "1.0"
futures = { version = "0.3", optional = true }
http = "0.2"
hyper = { version = "0.14", features = [ "full" ], optional = true }
percent-encoding = "2.1"
rustyline = "7"
textwrap = "0.11"
tokio = { version = "1.0", features = [], optional = true }
tokio-stream = { version = "0.1.1", optional = true }
url = "2.1"
#regex, serde, serde_json

# Macro crates:
proxmox-api-macro = { path = "../proxmox-api-macro", optional = true, version = "0.5.1" }
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true, version = "0.1.1" }

[features]
default = [ "cli", "router" ]
sortable-macro = ["proxmox-sortable-macro"]

# api:
api-macro = ["proxmox-api-macro"]
test-harness = []
cli = [ "router", "hyper", "tokio" ]
router = [ "futures", "hyper", "tokio" ]

examples = ["tokio/macros"]

# tools:
#valgrind = ["proxmox-tools/valgrind"]
