[package]
name = "proxmox"
edition = "2018"
version = "0.1.0"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
proxmox-api = { path = "../proxmox-api" }
proxmox-api-macro = { path = "../proxmox-api-macro", optional = true }
proxmox-sys = { path = "../proxmox-sys" }
proxmox-tools = { path = "../proxmox-tools" }
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true }

[features]
default = []
valgrind = ["proxmox-tools/valgrind"]
api-macro = ["proxmox-api-macro"]
sortable-macro = ["proxmox-sortable-macro"]
