[package]
name = "proxmox-system-management-api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true
description = "System Management API implementation (DNS, Time, Network)"

[dependencies]
anyhow.workspace = true
const_format.workspace = true
lazy_static.workspace = true
regex.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
nix = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
log = { workspace = true, optional = true }

proxmox-sys = { workspace = true, optional = true }
proxmox-schema = { workspace = true, features = ["api-macro", "api-types"] }
proxmox-time = { workspace = true, optional = true }
proxmox-product-config = { workspace = true, optional = true }

[features]
default = []
dns-api-types = ["dep:proxmox-product-config"]
dns-impl = [
    "dns-api-types",
    "dep:proxmox-product-config",
    "proxmox-product-config?/impl",
    "dep:proxmox-sys",
    "dep:proxmox-time",
]
time-api-types = []
time-impl = [
    "time-api-types",
    "dep:proxmox-product-config",
    "proxmox-product-config?/impl",
    "dep:proxmox-sys",
    "dep:proxmox-time",
]
network-api-types = []
network-impl = [
    "network-api-types",
    "dep:proxmox-product-config",
    "proxmox-product-config?/impl",
    "dep:nix",
    "dep:libc",
    "dep:proxmox-sys",
]
syslog-api-types = []
syslog-impl = [
    "syslog-api-types",
    "dep:log",
]
