[package]
name = "proxmox-async"
version = "0.4.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Proxmox async/tokio helpers"

exclude.workspace = true

[dependencies]
anyhow = "1.0"
futures = "0.3"
lazy_static = "1.4"
pin-utils = "0.1.0"
tokio = { version = "1.0", features = [ "net", "rt", "rt-multi-thread", "sync"] }

proxmox-io = { path = "../proxmox-io", version = "1", features = [ "tokio" ] }
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }

[dev-dependencies]
tokio = { version = "1.6", features = [ "macros" ] }
