[package]
name = "proxmox-async"
version = "0.4.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Proxmox async/tokio helpers"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
lazy_static.workspace = true
pin-utils = "0.1.0"
tokio = { workspace = true, features = [ "net", "rt", "rt-multi-thread", "sync"] }

proxmox-io = { path = "../proxmox-io", version = "1", features = [ "tokio" ] }
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }

[dev-dependencies]
tokio = { workspace = true, features = [ "macros" ] }
