[package]
name = "proxmox-async"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "Proxmox async/tokio helpers"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
bytes = "1.0"
flate2 = "1.0"
futures = "0.3"
lazy_static = "1.4"
pin-utils = "0.1.0"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "sync"] }

proxmox = { version = "0.15.3", default-features = false, features = [ "tokio" ] }
proxmox-io = { version = "1", features = [ "tokio" ] }
