[package]
name = "proxmox-time"
version = "1.1.4"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "time utilities and TmEditor"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
bitflags = "1.2.1"
lazy_static = "1.4"
nom = "7"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
libc = { version = "0.2", features = [ "extra_traits" ] }

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
