[package]
name = "proxmox-time"
version = "1.1.4"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "time utilities and TmEditor"

exclude.workspace = true

[dependencies]
anyhow = "1.0"
bitflags = "1.2.1"
lazy_static = "1.4"
nom = "7"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
libc = { version = "0.2", features = [ "extra_traits" ] }

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
