[package]
name = "proxmox-login"
version = "0.1.0"
description = "proxmox product authentication api"
edition.workspace = true
license.workspace = true

exclude.workspace = true

[dependencies]
base64.workspace = true
percent-encoding.workspace = true
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true

# For webauthn types
webauthn-rs = { workspace = true, optional = true }

# For `Authentication::set_auth_headers`
http = { version = "0.2.4", optional = true }

[features]
default = []
webauthn = [ "dep:webauthn-rs" ]
http = ["dep:http"]
