[package]
name = "proxmox-sys"
version = "0.4.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "System tools (using nix)."

exclude.workspace = true

[dependencies]
anyhow = "1.0"
base64 = "0.13"
lazy_static = "1.4"
libc = "0.2.107"
log = "0.4.17"
nix = "0.24.1"
regex = "1.2"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
zstd = { version = "0.6", features = [ "bindgen" ], optional = true}

# Macro crates:
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true, version = "0.1.2" }

proxmox-io = { path = "../proxmox-io", version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }
proxmox-time = { path = "../proxmox-time", version = "1.0.0" }

[features]
default = []
sortable-macro = ["dep:proxmox-sortable-macro"]
logrotate = ["dep:zstd"]
acl = []
crypt = []
timer = []
