[package]
name = "proxmox-sys"
version = "0.4.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "System tools (using nix)."

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
regex = "1.2"
serde_json.workspace = true
serde = { workspace = true, features = [ "derive" ] }
zstd = { workspace = true, optional = true}

# Macro crates:
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true, version = "0.1.2" }

proxmox-io = { path = "../proxmox-io", version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }
proxmox-time = { path = "../proxmox-time", version = "1.0.0" }

[features]
default = []
sortable-macro = ["dep:proxmox-sortable-macro"]
logrotate = ["dep:zstd"]
acl = []
crypt = []
timer = []
