[package]
name = "proxmox-sys"
edition = "2018"
version = "0.1.0"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
failure = "0.1"
lazy_static = "1.1"
libc = "0.2"
proxmox-tools = { path = "../proxmox-tools" }

# Docs should be able to reference the proxmox crate.
[dev-dependencies]
proxmox = { path = "../proxmox" }
