[package]
name = "proxmox-sys"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "System tools (using nix)."

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
base64 = "0.12"
libc = "0.2.107"
log = "0.4"
nix = "0.19.1"
zstd = { version = "0.6", features = [ "bindgen" ] }

proxmox = { path = "../proxmox", version = "0.15", default-features = false }
