[package]
name = "proxmox-sys"
edition = "2018"
version = "0.1.2"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
license = "AGPL-3"
description = "Proxmox system library"

exclude = [ "debian" ]

[dependencies]
failure = "0.1"
lazy_static = "1.4"
libc = "0.2"
nix = "0.16"
proxmox-tools = { version = "0.1.2", path = "../proxmox-tools" }

# Docs should be able to reference the proxmox crate.
[dev-dependencies]
proxmox = { path = "../proxmox" }
