[package]
name = "proxmox-sys"
version = "0.2.1"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "System tools (using nix)."

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
base64 = "0.13"
lazy_static = "1.4"
libc = "0.2.107"
log = "0.4"
nix = "0.19.1"
regex = "1.2"
serde_json = "1.0"
zstd = { version = "0.6", features = [ "bindgen" ] }

# Macro crates:
proxmox-sortable-macro = { path = "../proxmox-sortable-macro", optional = true, version = "0.1.1" }

proxmox-io = { path = "../proxmox-io", version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", version = "1.0.0" }
proxmox-borrow = { path = "../proxmox-borrow", version = "1.0.0" }
proxmox-time = { path = "../proxmox-time", version = "1.0.0" }

[features]
default = []
sortable-macro = ["proxmox-sortable-macro"]
