[package]
name = "proxmox-uuid"
version = "1.0.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "bindings for libuuid with optional serde support"

exclude = [ "debian" ]

[dependencies]
libc = "0.2"
serde = { version = "1.0", optional = true }

[features]
default = []

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
