[package]
name = "proxmox-uuid"
version = "1.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "bindings for libuuid with optional serde support"

exclude.workspace = true

[dependencies]
libc = "0.2"
serde = { version = "1.0", optional = true }

[features]
default = []

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
