[package]
name = "proxmox-serde"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Serde formatting tools"

exclude.workspace = true

[dependencies]
anyhow = "1.0"
base64 = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

proxmox-time = { path = "../proxmox-time", version = "1.0.0" }

[dev-dependencies]
serde_json = "1.0"
