[package]
name = "proxmox-metrics"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "Metrics Server export utilitites"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = [ "net", "sync" ] }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
http = "0.2"
hyper = "0.14"
openssl = "0.10"
proxmox-http = { path = "../proxmox-http", features = [ "client" ], version = "0.6" }
proxmox-async = { path = "../proxmox-async", features = [], version = "0.3" }
