[package]
name = "proxmox-metrics"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Metrics Server export utilitites"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
http.workspace = true
hyper.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = [ "net", "sync" ] }

proxmox-async.workspace = true
proxmox-http = { workspace = true, features = [ "client" ] }
