[package]
name = "proxmox-metrics"
version = "0.2.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Metrics Server export utilitites"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
http.workspace = true
hyper.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = [ "net", "sync" ] }

proxmox-async = { path = "../proxmox-async", features = [], version = "0.4" }
proxmox-http = { path = "../proxmox-http", features = [ "client" ], version = "0.7" }
