[package]
name = "proxmox-schema"
version = "1.3.5"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "proxmox api schema and validation"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
lazy_static.workspace = true
regex = "1.5"
serde.workspace = true
serde_json.workspace = true
textwrap = "0.16"

# the upid type needs this for 'getpid'
libc = { workspace = true, optional = true }
nix = { workspace = true, optional = true }

proxmox-api-macro = { path = "../proxmox-api-macro", optional = true, version = "1.0.3" }

[dev-dependencies]
url.workspace = true
serde = { workspace = true, features = [ "derive" ] }
proxmox-api-macro = { path = "../proxmox-api-macro", version = "1.0.3" }

[features]
default = []

api-macro = ["dep:proxmox-api-macro"]
upid-api-impl = [ "dep:libc", "dep:nix" ]

# Testing only
test-harness = []
