[package]
name = "proxmox-schema"
version = "1.3.5"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "proxmox api schema and validation"

exclude.workspace = true

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
regex = "1.5"
serde = "1.0"
serde_json = "1.0"
textwrap = "0.16"

# the upid type needs this for 'getpid'
libc = { version = "0.2", optional = true }
nix = { version = "0.24.1", optional = true }

proxmox-api-macro = { path = "../proxmox-api-macro", optional = true, version = "1.0.3" }

[dev-dependencies]
url = "2.1"
serde = { version = "1.0", features = [ "derive" ] }
proxmox-api-macro = { path = "../proxmox-api-macro", version = "1.0.3" }

[features]
default = []

api-macro = ["dep:proxmox-api-macro"]
upid-api-impl = [ "dep:libc", "dep:nix" ]

# Testing only
test-harness = []
