[package]
name = "proxmox-api-macro"
edition = "2018"
version = "0.1.0"
authors = [ "Wolfgang Bumiller <w.bumiller@proxmox.com>" ]

[lib]
proc-macro = true

[dependencies]
failure = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "full" ] }

[dev-dependencies]
futures = "0.3"
proxmox = { path = "../proxmox" }
proxmox-api = { path = "../proxmox-api", features = [ "test-harness" ] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
