[package]
name = "proxmox-tools"
edition = "2018"
version = "0.1.1"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]

[dependencies]
base64 = "0.10"
chrono = "0.4"
endian_trait = { version = "0.6", features = ["arrays"] }
failure = "0.1"
lazy_static = "1.4"
libc = "0.2"
nix = "0.16"
regex = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
valgrind_request = { git = "https://github.com/edef1c/libvalgrind_request", version = "1.1.0", optional = true }

[features]
default = []
valgrind = [ "valgrind_request" ]

# Docs should be able to reference the proxmox crate.
[dev-dependencies]
proxmox = { path = "../proxmox" }
