[package]
name = "proxmox-http"
edition.workspace = true
version = "0.7.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Proxmox HTTP library"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64 = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
http = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
openssl =  { version = "0.10", optional = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = [], optional = true }
tokio-openssl = { workspace = true, optional = true }
ureq = { version = "2.4", features = ["native-certs"], optional = true }
url = { workspace = true, optional = true }

proxmox-async = { path = "../proxmox-async", optional = true, version = "0.4.1" }
proxmox-sys = { path = "../proxmox-sys", optional = true, version = "0.4" }
proxmox-io = { path = "../proxmox-io", optional = true, version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", optional = true, version = "1.1" }

[features]
default = []

client = [ "dep:futures", "http-helpers", "dep:hyper", "hyper?/full", "dep:openssl", "dep:tokio", "tokio?/io-util", "dep:tokio-openssl" ]
client-sync = [ "client-trait", "http-helpers", "dep:ureq" ]
client-trait = [ "dep:http" ]
http-helpers = [ "dep:base64", "dep:http", "dep:proxmox-sys", "dep:serde_json", "dep:url" ]
websocket = [
    "dep:base64",
    "dep:futures",
    "dep:hyper",
    "dep:openssl",
    "dep:proxmox-sys",
    "dep:proxmox-io",
    "proxmox-io?/tokio",
    "dep:proxmox-lang",
    "dep:tokio",
    "tokio?/io-util",
    "tokio?/sync",
]
