[package]
name = "proxmox-http"
edition = "2018"
version = "0.6.1"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
license = "AGPL-3"
description = "Proxmox HTTP library"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
base64 = { version = "0.13", optional = true }
futures = { version = "0.3", optional = true }
http = { version = "0.2", optional = true }
hyper = { version = "0.14", features = [ "full" ], optional = true }
openssl =  { version = "0.10", optional = true }
tokio = { version = "1.0", features = [], optional = true }
tokio-openssl = { version = "0.6.1", optional = true }

proxmox-sys = { path = "../proxmox-sys", optional = true, version = "0.3.0" }
proxmox-io = { path = "../proxmox-io", optional = true, version = "1.0.0" }
proxmox-lang = { path = "../proxmox-lang", optional = true, version = "1.1" }

[features]
default = []

client = [ "futures", "http-helpers", "openssl" ]
http-helpers = [ "base64", "http", "hyper", "tokio/io-util", "tokio-openssl", "proxmox-sys" ]
websocket = [
    "base64",
    "futures",
    "hyper",
    "openssl",
    "proxmox-sys",
    "proxmox-io/tokio",
    "proxmox-lang",
    "tokio/io-util",
    "tokio/sync",
]
