[package]
name = "proxmox-shared-memory"
version = "0.2.1"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "Shared memory helpers and shared mutex implementation"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
libc = "0.2.107"
nix = "0.24.1"

proxmox-sys = { path = "../proxmox-sys", version = "0.3.0" }
