[package]
name = "proxmox-shared-memory"
version = "0.2.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared memory helpers and shared mutex implementation"

exclude.workspace = true

[dependencies]
anyhow = "1.0"
libc = "0.2.107"
nix = "0.24.1"

proxmox-sys = { path = "../proxmox-sys", version = "0.4" }
