[package]
name = "proxmox-shared-memory"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "Shared memory helpers and shared mutex implementation"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
libc = "0.2.107"
nix = "0.19.1"

proxmox = { path = "../proxmox", version = "0.15", default-features = false }
