[package]
name = "proxmox-subscription"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Proxmox subscription utilitites"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
hex.workspace = true
lazy_static.workspace = true
openssl.workspace = true
regex = "1.5"
serde.workspace = true
serde_json.workspace = true

proxmox-http = { path = "../proxmox-http", version = "0.7", default_features = false, features = ["client-trait", "http-helpers"] }
proxmox-serde = { path = "../proxmox-serde", version = "0.1.1", features = ["serde_json"]}
proxmox-sys = { path = "../proxmox-sys", version = "0.4" }
proxmox-time = { path = "../proxmox-time", version = "1.1" }

proxmox-schema = { path = "../proxmox-schema", version = "1.3.3", features = ["api-macro"], optional = true }

[features]
default = []
api-types = ["dep:proxmox-schema"]
