[package]
name = "proxmox-section-config"
version = "1.0.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "proxmox schema based section config format parsing"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true

proxmox-schema = { path = "../proxmox-schema", version = "1.1" }
# FIXME: remove!
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }
