[package]
name = "proxmox-section-config"
version = "1.0.1"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "proxmox schema based section config format parsing"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"

proxmox-schema = { path = "../proxmox-schema", version = "1.1" }
# FIXME: remove!
proxmox-lang = { path = "../proxmox-lang", version = "1.1" }
