[package]
name = "proxmox-lang"
version = "1.0.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "simple rust language utilities such as try_block, which have no dependencies"

exclude = [ "debian" ]

[dependencies]
