[package]
name = "proxmox-io"
version = "1.0.1"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "extension traits for Read and Write"

exclude = [ "debian" ]

[dependencies]
endian_trait = { version = "0.6", features = ["arrays"] }
# this is also the feature name:
tokio = { version = "1.0", features = [ "io-util" ], optional = true }
