[package]
name = "proxmox-rest-server"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "REST server implementation"

exclude.workspace = true

[dev-dependencies]
proxmox-schema = { version = "1.3.1", features = [ "api-macro" ] }
tokio = { workspace = true, features = [ "rt-multi-thread", "signal", "process" ] }

[dependencies]
anyhow.workspace = true
futures.workspace = true
handlebars = "3.0"
http.workspace = true
hyper = { workspace = true, features = [ "full" ] }
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
once_cell = "1.3.1"
percent-encoding.workspace = true
regex = "1.5"
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
tokio = { workspace = true, features = ["signal", "process"] }
tokio-openssl.workspace = true
tokio-stream = "0.1.0"
tower-service = "0.3.0"
url.workspace = true

#proxmox = "0.15.3"
proxmox-async = "0.4"
proxmox-compression = "0.1.1"
proxmox-io = "1"
proxmox-lang = "1.1"
proxmox-http = { version = "0.7", features = [ "client" ] }
proxmox-router = "1.3.0"
proxmox-schema = { version = "1.3.1", features = [ "api-macro", "upid-api-impl" ] }
proxmox-time = "1"
proxmox-sys = { version = "0.4", features = [ "logrotate", "timer" ] }
