[package]
name = "proxmox-router"
version = "1.2.4"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "proxmox API Router and CLI utilities"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
env_logger = { version = "0.9", optional = true }
http = { version = "0.2", optional = true }
hyper = { version = "0.14", features = [ "full" ], optional = true }
nix = "0.24.1"
percent-encoding = "2.1"
serde_json = "1.0"
serde = "1.0"
unicode-width ="0.1.8"

# cli:
tokio = { version = "1.0", features = [], optional = true }
rustyline = { version = "9", optional = true }
libc = { version = "0.2", optional = true }

proxmox-lang = { path = "../proxmox-lang", version = "1.1" }
proxmox-schema = { path = "../proxmox-schema", version = "1.1" }
proxmox-async = { path = "../proxmox-async", version = "0.4.1" }

[features]
default = [ "cli", "server" ]
cli = [ "dep:env_logger", "dep:libc", "dep:rustyline", "dep:tokio" ]
server = [ "dep:http", "dep:hyper" ]
test-harness = [ "proxmox-schema/test-harness" ]
