[package]
name = "proxmox-router"
version = "1.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
license = "AGPL-3"
description = "proxmox API Router and CLI utilities"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
http = "0.2"
hyper = { version = "0.14", features = [ "full" ] }
nix = "0.19.1"
percent-encoding = "2.1"
serde_json = "1.0"
unicode-width ="0.1.8"

# cli:
tokio = { version = "1.0", features = [], optional = true }
rustyline = { version = "7", optional = true }
libc = { version = "0.2", optional = true }

proxmox-lang = { path = "../proxmox-lang", version = "1.0" }
proxmox-schema = { path = "../proxmox-schema", version = "1.0" }

[features]
default = [ "cli" ]
cli = [ "libc", "rustyline", "tokio" ]
test-harness = [ "proxmox-schema/test-harness" ]
