[package]
name = "proxmox-acme"
version = "0.4.0"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2021"
license = "AGPL-3"
description = "ACME client library"
exclude = [
    "build",
    "debian",
]

[dependencies]
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = "0.10.29"

# For the client
native-tls = { version = "0.2", optional = true }

[dependencies.ureq]
optional = true
version = "2.4"
default-features = false
features = [ "native-tls", "gzip" ]

[features]
default = []
client = ["ureq", "native-tls"]

[dev-dependencies]
anyhow = "1.0"
